version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
    env_file: ./.env
    volumes:
      - .:/usr/src
      - /usr/node_modules
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - data:/var/lib/redis
volumes:
  data:
    driver: local
